packages:
  - frontend
  - packages/*

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@marimo-team/*'
  - yaml@2.8.3
  - path-to-regexp@8.4.0

onlyBuiltDependencies: '@swc/core,esbuild,msw,es5-ext,spawn-sync'

verifyDepsBeforeRun: install
